name: tbdex
description: Dart library for tbDEX.
version: 1.0.0
repository: https://github.com/TBD54566975/tbdex-dart

publish_to: none

environment:
  sdk: ^3.1.4

dependencies:
  crypto: ^3.0.3
  decimal: ^2.3.3
  http: ^1.2.0
  json_schema: ^5.1.3
  mocktail: ^1.0.3
  path: ^1.8.3
  typeid: ^1.0.1
  web5: ^0.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
